/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as ProjelerIndexRouteImport } from './routes/projeler.index'
import { Route as ProjelerSlugRouteImport } from './routes/projeler.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerIndexRoute = ProjelerIndexRouteImport.update({
  id: '/projeler/',
  path: '/projeler/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerSlugRoute = ProjelerSlugRouteImport.update({
  id: '/projeler/$slug',
  path: '/projeler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/projeler/$slug': typeof ProjelerSlugRoute
  '/projeler/': typeof ProjelerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/projeler/$slug': typeof ProjelerSlugRoute
  '/projeler': typeof ProjelerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/iletisim': typeof IletisimRoute
  '/projeler/$slug': typeof ProjelerSlugRoute
  '/projeler/': typeof ProjelerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/hakkimizda' | '/iletisim' | '/projeler/$slug' | '/projeler/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/hakkimizda' | '/iletisim' | '/projeler/$slug' | '/projeler'
  id:
    | '__root__'
    | '/'
    | '/hakkimizda'
    | '/iletisim'
    | '/projeler/$slug'
    | '/projeler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  IletisimRoute: typeof IletisimRoute
  ProjelerSlugRoute: typeof ProjelerSlugRoute
  ProjelerIndexRoute: typeof ProjelerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeler/': {
      id: '/projeler/'
      path: '/projeler'
      fullPath: '/projeler/'
      preLoaderRoute: typeof ProjelerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeler/$slug': {
      id: '/projeler/$slug'
      path: '/projeler/$slug'
      fullPath: '/projeler/$slug'
      preLoaderRoute: typeof ProjelerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  IletisimRoute: IletisimRoute,
  ProjelerSlugRoute: ProjelerSlugRoute,
  ProjelerIndexRoute: ProjelerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
