/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HakkimizdaRouteImport } from './routes/hakkimizda'
import { Route as HizmetlerimizRouteImport } from './routes/hizmetlerimiz'
import { Route as IletisimRouteImport } from './routes/iletisim'
import { Route as MisyonumuzRouteImport } from './routes/misyonumuz'
import { Route as VizyonumuzRouteImport } from './routes/vizyonumuz'
import { Route as ProjelerIndexRouteImport } from './routes/projeler.index'
import { Route as ProjelerSlugRouteImport } from './routes/projeler.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HakkimizdaRoute = HakkimizdaRouteImport.update({
  id: '/hakkimizda',
  path: '/hakkimizda',
  getParentRoute: () => rootRouteImport,
} as any)
const HizmetlerimizRoute = HizmetlerimizRouteImport.update({
  id: '/hizmetlerimiz',
  path: '/hizmetlerimiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IletisimRoute = IletisimRouteImport.update({
  id: '/iletisim',
  path: '/iletisim',
  getParentRoute: () => rootRouteImport,
} as any)
const MisyonumuzRoute = MisyonumuzRouteImport.update({
  id: '/misyonumuz',
  path: '/misyonumuz',
  getParentRoute: () => rootRouteImport,
} as any)
const VizyonumuzRoute = VizyonumuzRouteImport.update({
  id: '/vizyonumuz',
  path: '/vizyonumuz',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerIndexRoute = ProjelerIndexRouteImport.update({
  id: '/projeler/',
  path: '/projeler/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjelerSlugRoute = ProjelerSlugRouteImport.update({
  id: '/projeler/$slug',
  path: '/projeler/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetlerimiz': typeof HizmetlerimizRoute
  '/iletisim': typeof IletisimRoute
  '/misyonumuz': typeof MisyonumuzRoute
  '/vizyonumuz': typeof VizyonumuzRoute
  '/projeler/$slug': typeof ProjelerSlugRoute
  '/projeler/': typeof ProjelerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetlerimiz': typeof HizmetlerimizRoute
  '/iletisim': typeof IletisimRoute
  '/misyonumuz': typeof MisyonumuzRoute
  '/vizyonumuz': typeof VizyonumuzRoute
  '/projeler/$slug': typeof ProjelerSlugRoute
  '/projeler': typeof ProjelerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/hakkimizda': typeof HakkimizdaRoute
  '/hizmetlerimiz': typeof HizmetlerimizRoute
  '/iletisim': typeof IletisimRoute
  '/misyonumuz': typeof MisyonumuzRoute
  '/vizyonumuz': typeof VizyonumuzRoute
  '/projeler/$slug': typeof ProjelerSlugRoute
  '/projeler/': typeof ProjelerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/hakkimizda'
    | '/hizmetlerimiz'
    | '/iletisim'
    | '/misyonumuz'
    | '/vizyonumuz'
    | '/projeler/$slug'
    | '/projeler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/hakkimizda'
    | '/hizmetlerimiz'
    | '/iletisim'
    | '/misyonumuz'
    | '/vizyonumuz'
    | '/projeler/$slug'
    | '/projeler'
  id:
    | '__root__'
    | '/'
    | '/hakkimizda'
    | '/hizmetlerimiz'
    | '/iletisim'
    | '/misyonumuz'
    | '/vizyonumuz'
    | '/projeler/$slug'
    | '/projeler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HakkimizdaRoute: typeof HakkimizdaRoute
  HizmetlerimizRoute: typeof HizmetlerimizRoute
  IletisimRoute: typeof IletisimRoute
  MisyonumuzRoute: typeof MisyonumuzRoute
  VizyonumuzRoute: typeof VizyonumuzRoute
  ProjelerSlugRoute: typeof ProjelerSlugRoute
  ProjelerIndexRoute: typeof ProjelerIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hakkimizda': {
      id: '/hakkimizda'
      path: '/hakkimizda'
      fullPath: '/hakkimizda'
      preLoaderRoute: typeof HakkimizdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hizmetlerimiz': {
      id: '/hizmetlerimiz'
      path: '/hizmetlerimiz'
      fullPath: '/hizmetlerimiz'
      preLoaderRoute: typeof HizmetlerimizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iletisim': {
      id: '/iletisim'
      path: '/iletisim'
      fullPath: '/iletisim'
      preLoaderRoute: typeof IletisimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/misyonumuz': {
      id: '/misyonumuz'
      path: '/misyonumuz'
      fullPath: '/misyonumuz'
      preLoaderRoute: typeof MisyonumuzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vizyonumuz': {
      id: '/vizyonumuz'
      path: '/vizyonumuz'
      fullPath: '/vizyonumuz'
      preLoaderRoute: typeof VizyonumuzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeler/': {
      id: '/projeler/'
      path: '/projeler'
      fullPath: '/projeler/'
      preLoaderRoute: typeof ProjelerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projeler/$slug': {
      id: '/projeler/$slug'
      path: '/projeler/$slug'
      fullPath: '/projeler/$slug'
      preLoaderRoute: typeof ProjelerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HakkimizdaRoute: HakkimizdaRoute,
  HizmetlerimizRoute: HizmetlerimizRoute,
  IletisimRoute: IletisimRoute,
  MisyonumuzRoute: MisyonumuzRoute,
  VizyonumuzRoute: VizyonumuzRoute,
  ProjelerSlugRoute: ProjelerSlugRoute,
  ProjelerIndexRoute: ProjelerIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
